### ISSUE TITLE
Conversational Awareness and Adaptive Transparency support

### ISSUE THREAD

**Issue by kavishdevar** [steam3d/MagicPodsCore#11]
Capture conversational awareness to reduce volume automatically.

There are specific packets that the airpods send when the person wearing them starts speaking, but those are not received when media is playing. Let alone that, the airpods don't even switch to transparency mode during playback like they do when no media is playing, and/or on apple devices.

**Comment by kavishdevar** [comment]
I am able to set Adaptive Transparency using the same packet used to set other anc modes (8th byte as 04), but the airpods respond (when i send the packet or long press the button) with a 02 (which is for ANC on) instead of 04. This might be becasue a different initialization packet is being sent by apple devices.

**Comment by kavishdevar** [comment]
nvm, I tried sending all the init pacets that my 2015 MBA sends, and adaptive transparency responses work! I'll try and figure out which one is needed and update later

**Comment by steam3d** [comment]
I implemented adaptive transparency, but I can't figure out how to receive notifications from AirPods when the user starts speaking to lower the music volume level.

**Comment by kavishdevar** [comment]
Sending `04 00 04 00 0F 00 FF FF FE FF` instead of `04 00 04 00 0F 00 FF FF FF FF` fixes both.

**Comment by kavishdevar** [comment]
nvm, this packet needs to be sent `04 00 04 00 4d 00 ff 00 00 00 00 00 00 00` before/after the notification filter mentioned above
